### ISSUE TITLE
failed to get data

### ISSUE THREAD

**Issue by boyac** [pmorissette/bt#73]
import bt 
# get data

data = bt.get('spy,agg', start='2010-01-01')
print data.head()

AttributeError: 'module' object has no attribute 'decorator'

By the way, is the data source from yahoo finance?
And is the price of spy, agg close prices?

Thanks

**Comment by aaronroman** [comment]
It's working for me, check your versions:

python 3.5
pandas==0.19.0
bt==0.1.14
pandas-datareader==0.2.1

**Comment by boyac** [comment]
Thanks. I'm using python 2.7. Is it possible to run in python 2.7?

**Comment by pmorissette** [comment]
@boyac please update `bt` and report back if you are still having issues. `bt` does work with python 2.7.

Thanks,
Phil

**Comment by boyac** [comment]
@pmorissette  ok, Thanks!
